services:
  # Development environment
  nmrium-dev:
    container_name: nmrium-dev
    image: nfdi4chem/nmrium-react-wrapper:dev-latest
    restart: always
    ports:
      - "81:80"
    networks:
      - nmrium-network
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  # Production environment
  nmrium-prod:
    container_name: nmrium-prod
    image: nfdi4chem/nmrium-react-wrapper:latest
    restart: always
    ports:
      - "80:80"
    networks:
      - nmrium-network
    environment:
      - NODE_ENV=production
      - RELEASE_VERSION=latest

networks:
  nmrium-network:
    driver: bridge 