# build environment
FROM node:22-alpine3.18 as build

# ARG RELEASE_VERSION
# ENV RELEASE_VERSION=${RELEASE_VERSION}

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
RUN export NODE_OPTIONS=--max-old-space-size=8192
RUN npm i --silent
RUN npm i react-scripts@latest -g --silent
COPY . ./
RUN echo "export default { version: '$RELEASE_VERSION' };" > src/versionInfo.ts
RUN npm run build -- --outDir=build
RUN npm run build -- --outDir=build/releases/v0.0.1

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]