services:
  # Development environment
  nmrium-dev:
    container_name: nmrium-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "81:80"
    restart: always
    networks:
      - nmrium-network
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  # Production environment
  nmrium-prod:
    container_name: nmrium-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - RELEASE_VERSION=latest
    ports:
      - "80:80"
    restart: always
    networks:
      - nmrium-network

networks:
  nmrium-network:
    driver: bridge 