version: '3.7'

services:
  # Development environment
  nmrium-dev:
    container_name: nmrium-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    networks:
      - nmrium-network
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  # Production environment
  nmrium-prod:
    container_name: nmrium-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    networks:
      - nmrium-network
    environment:
      - NODE_ENV=production
      - RELEASE_VERSION=latest

  # Nginx reverse proxy
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:stable-alpine
    ports:
      - "8080:80"  # Dev environment on port 8080
      - "8081:81"  # Prod environment on port 8081
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nmrium-dev
      - nmrium-prod
    networks:
      - nmrium-network

networks:
  nmrium-network:
    driver: bridge 