# build environment
FROM node:18-alpine3.14 as build

ARG RELEASE_VERSION
ENV RELEASE_VERSION=${RELEASE_VERSION}

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN export NODE_OPTIONS=--max-old-space-size=8192
RUN npm ci --silent
RUN npm install react-scripts@latest -g --silent
COPY . ./
RUN npm run build -- --outDir=build
RUN npm run build -- --outDir=build/releases/${RELEASE_VERSION}

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]